"""add foreign keys to message to_id and from_id

Revision ID: 19e678456382
Revises: 710f1592793e
Create Date: 2024-10-22 01:05:07.900208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e678456382'
down_revision: Union[str, None] = '710f1592793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['from_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
